---
ID: "40dc4477-0ff2-40af-8977-733efc601d8b"
Parent: "3d6ff80e-32e2-412c-b0bc-216e8d035c6a"
Template: "3d6ff80e-32e2-412c-b0bc-216e8d035c6a"
Path: /sitecore/templates/Foundation/CssPicker/_CssPicker/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170716T125825Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
